# node-port
# exposes our dotnet server in local port 30010
apiVersion: v1
kind: Service
metadata:
  name: np-dotnet-server
  labels:
    app: dotnet-server
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30010
  selector:
    app: dotnet-server
---
# exposes our dotnet pgsql db in local port 30007
apiVersion: v1
kind: Service
metadata:
  name: pgsql-np-dotnet
  labels:
    app: postgres-dotnet
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30007
  selector:
    app: dotnet-server
---
#exposes our rails pgsql at port 30006
apiVersion: v1
kind: Service
metadata:
  name: pgsql-np-ruby
  labels:
    app: postgres-rails
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30006
  selector:
    app: postgres-rails
